### PR TITLE
Added WOL and Docker support 

### PR DESCRIPTION
**Pull request by Sneaker15**
Hi there,

I added two features that I needed for my home setup.

1. WOL support: I need my dash buttons as a convenient way of waking a machine (e.g. a media file server that's typically in suspend or powered off). 
2. Docker support: I tend to have all services / daemons running containerized. There's a repository with clemenstyp/dasher-docker available but I preferred to have one that a) is built on top of official Node image and b) comes with a prescription on docker-compose (it took me a while to figure out the right settings and now it's just a single statement)

Feel free to incorporate the changes into yours. I would appreciate any feedback.

Thanks!

### CODE REVIEW

**Comment by droberts84** [comment]
👍  for Docker support

Is Docker compose required though?  If so would it possible to make it optional?  I run docker containers on a NAS (and I'm sure many other users do), so it may not be as straight forward to use docker compose

**Comment by Sneaker15** [comment]
Docker compose isn't required but I tend to use it since it provides me a nice way to launch containers in pre-configured way. 

I haven't tried but following 2 commands should be equivalent, The first will build and the second command launch the container:

docker build -t mydasher .

docker run -d --name=dasher --restart=always --net=host -v ./config:/usr/src/app/config mydasher

**Comment by mutzl** [comment]
I am having a hard time with docker...
Building this on Docker for Windows brings up errors and I have not found out yet, how to create docker images on my Synology NAS. 
Could someone provide an image on docker hub, please?

**Comment by droberts84** [comment]
I've been using https://hub.docker.com/r/clemenstyp/dasher-docker/

**Comment by mutzl** [comment]
Thanks droberts84!
I tried that already and was not able to map to my custom config.json file. ;(

**Comment by Sneaker15** [comment]
Latest project enhancements made me choose to follow a separate path (adding etherwake cmd instead of wol npm package). Regardless of the fact, I created a [separate repository](https://github.com/Sneaker15/docker-dasher) for those who're still interested in a dockerized version including WOL

**Pull request closed without merging**
